project:
  type: book
  output-dir: docs
  
book:
  title: "Hands-On Programming with R"
  author: "Garrett Grolemund"
  cover-image: images/cover.png
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/jjallaire/hopr/
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - part: dice.qmd
      chapters: 
        - basics.qmd
        - packages.qmd
    - part: cards.qmd
      chapters:
        - objects.qmd
        - notation.qmd
        - modifying.qmd
        - environments.qmd
    - part: slots.qmd
      chapters:
        - programs.qmd
        - s3.qmd
        - loops.qmd
        - speed.qmd
  appendices:
    - a1-starting.qmd
    - a2-packages.qmd
    - a3-updating.qmd
    - a4-data.qmd
    - a5-debug.qmd 

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true
  pdf:
    documentclass: scrbook
    papersize: letter
    classoption: [DIV=11, numbers=noendperiod]
    include-in-header: 
      text: |
        \usepackage{tikz}
        \usepackage{graphicx}
        \newcommand{\circled}[1]{\tikz[baseline=(char.base)]{\node[shape=circle,draw,inner sep=1pt] (char) {#1};}}
    top-level-division: chapter
    include-before-body:
      text: |
        \frontmatter
        \begin{titlepage}
        \thispagestyle{empty}
        \begin{center}
        \vspace*{2cm}
        {\Huge\bfseries Hands-On Programming with R\par}
        \vspace{2cm}
        {\Large\itshape Garrett Grolemund\par}
        \vfill
        \includegraphics[width=0.8\textwidth]{images/cover.png}
        \vfill
        \end{center}
        \end{titlepage}
        \cleardoublepage
        \mainmatter
    keep-tex: true
    block-headings: true
    toc: true
    number-sections: true
    colorlinks: true


